
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ErrorWrapper } from "./error-wrapper"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata :Metadata = {
  title:{
    default:"nextjs-implementation",
    template:"%s | Next-app",
  },
  description: "Generated by create next app",
}
  
export default function RootLayout({children,}:{children:React.ReactNode}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header style={{
      backgroundColor:"lightblue",

      padding:"35px",
        }}>
        <p>Next-app</p>
      </header>
        <ErrorWrapper>{children}</ErrorWrapper>
        <footer style={{
      backgroundColor:"ghostWhite",
    
      padding:"1rem"
        }}>
      <p> Footer </p>
        </footer>
      </body>
    </html>
  );
}
