import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: {children:React.ReactNode;}) {
  return (
    <html
      lang="en">
      <body>
        <header style ={{
      backgroundColor: "Lightblue",
      padding:"1rem",
        }}>
        <p>Auth header </p>
      </header>
        {children}
        <footer style={{
      backgroundColor:"gray",
      padding:"1rem",
        }}>
      <p> Auth Footer </p>
        </footer>
      </body>
    </html>
  );
}
